services:
  - type: web
    name: nccer-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mock_dash_v2:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
